const INVAILD_ERROR = 400;
const NON_EXISTENT_ERROR = 404;
const DEFAULT_ERROR = 500;
const DUPLICATE_ERROR = 409;

module.exports = {
  INVAILD_ERROR,
  NON_EXISTENT_ERROR,
  DEFAULT_ERROR,
  DUPLICATE_ERROR,
};
